---
abstract: 'A complete GitLab API v4 client.'
author:
  - 'Aran Clary Deltac <bluefeet@gmail.com>'
build_requires:
  Log::Any::Adapter::TAP: '0.003003'
  MIME::Base64: '3.15'
  Test2::V0: '0.000094'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v3.1.11, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GitLab-API-v4
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  GitLab::API::v4:
    file: lib/GitLab/API/v4.pm
    version: '0.26'
  GitLab::API::v4::Config:
    file: lib/GitLab/API/v4/Config.pm
    version: '0.26'
  GitLab::API::v4::Constants:
    file: lib/GitLab/API/v4/Constants.pm
    version: '0.26'
  GitLab::API::v4::Mock:
    file: lib/GitLab/API/v4/Mock.pm
    version: '0.26'
  GitLab::API::v4::Mock::Engine:
    file: lib/GitLab/API/v4/Mock/Engine.pm
    version: '0.26'
  GitLab::API::v4::Mock::RESTClient:
    file: lib/GitLab/API/v4/Mock/RESTClient.pm
    version: '0.26'
  GitLab::API::v4::Paginator:
    file: lib/GitLab/API/v4/Paginator.pm
    version: '0.26'
  GitLab::API::v4::RESTClient:
    file: lib/GitLab/API/v4/RESTClient.pm
    version: '0.26'
  GitLab::API::v4::WWWClient:
    file: lib/GitLab/API/v4/WWWClient.pm
    version: '0.26'
requires:
  Carp: '0'
  Const::Fast: '0.014'
  Exporter: '0'
  Getopt::Long: '0'
  HTTP::Tiny: '0.059'
  HTTP::Tiny::Multipart: '0.05'
  IO::Prompter: '0.004014'
  JSON: '2.59'
  Log::Any: '1.703'
  Log::Any::Adapter: '1.703'
  Log::Any::Adapter::Screen: '0.13'
  Moo: '2.003000'
  Path::Tiny: '0.079'
  Pod::Usage: '0'
  Try::Tiny: '0.28'
  Types::Common::Numeric: '1.002001'
  Types::Common::String: '1.002001'
  Types::Standard: '1.002001'
  URI: '1.62'
  URI::Escape: '1.72'
  namespace::clean: '0.27'
  perl: '5.010001'
  strictures: '2.000003'
resources:
  bugtracker: https://github.com/bluefeet/GitLab-API-v4/issues
  homepage: https://github.com/bluefeet/GitLab-API-v4
  repository: git://github.com/bluefeet/GitLab-API-v4.git
version: '0.26'
x_authority: cpan:BLUEFEET
x_contributors:
  - 'Dave Webb <github@d5ve.com>'
  - 'Dmitry Frolov <dmitry.frolov@gmail.com>'
  - 'Dotan Dimet <dotan@corky.net>'
  - 'Graham Knop <haarg@haarg.org>'
  - 'José Joaquín Atria <jjatria@gmail.com>'
  - 'Kieren Diment <kieren.diment@staples.com.au>'
  - 'Luc Didry <luc@didry.org>'
  - 'Marek R. Sotola <Marek.R.Sotola@nasa.gov>'
  - 'Nigel Gregoire <nigelgregoire@gmail.com>'
  - 'Simon Ruderich <simon@ruderich.org>'
  - 'Thomas Klausner <domm@plix.at>'
  - 'gregor herrmann <gregoa@debian.org>'
  - 'royce55 <royce@ecs.vuw.ac.nz>'
  - 'trunov-ms <trunov.ms@gmail.com>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
